import {
    Activity,
    AlertCircle,
    Binoculars,
    BookUser,
    Calendar,
    FileText,
    Heart,
    Home,
    Pill,
    ShieldCheck,
    Stethoscope,
    Users
} from 'lucide-react';

export const MENU_ITEMS = [
    {
        id: 1,
        key: 'home',
        title: 'Home',
        icon: Home,
        route: '',
        active: false,
        roles: ['ADMIN', 'USER', 'DOCTOR'],
    },
    // {
    //     id: 2,
    //     key: 'USERs',
    //     title: 'USERs',
    //     icon: Users,
    //     route: '/USERs',
    //     active: false,
    //     roles: ['ADMIN', 'DOCTOR'],
    // },
    {
        id: 3,
        key: 'doctors',
        title: 'Doctors',
        icon: Stethoscope,
        route: '/doctors',
        active: false,
        roles: ['ADMIN'],
    },
    {
        id: 4,
        key: 'availability',
        title: 'Availability',
        icon: Calendar,
        route: '/availability',
        active: false,
        roles: ['ADMIN', 'DOCTOR'],
    },
    {
        id: 5,
        key: 'patientVisits',
        title: 'Patients Visits',
        icon: BookUser,
        route: '/patients',
        active: false,
        roles: ['ADMIN', 'DOCTOR'],
    },
    {
        id: 6,
        key: 'testTypes',
        title: 'Test Types',
        icon: Binoculars,
        route: '/tests',
        active: false,
        roles: ['ADMIN'],
    },
    {
        id: 7,
        key: 'documents',
        title: 'Documents',
        icon: FileText,
        route: '/documents',
        active: false,
        roles: ['ADMIN', 'USER'],
    },
    {
        id: 8,
        key: 'appointments',
        title: 'Appointments',
        icon: Activity,
        route: '/appointments',
        active: false,
        roles: ['ADMIN', 'DOCTOR', 'USER'],
    },
    {
        id: 9,
        key: 'prescription',
        title: 'Prescription',
        icon: Pill,
        route: '/prescription',
        active: false,
        roles: ['ADMIN', 'DOCTOR', 'USER'],
    },
    {
        id: 13,
        key: 'roles',
        title: 'Roles',
        icon: Users,
        route: '/roles',
        active: false,
        roles: ['ADMIN'],
    },
];
