import {
    Activity,
    AlertCircle,
    Binoculars,
    BookUser,
    Calendar,
    FileText,
    Heart,
    Home,
    Pill,
    ShieldCheck,
    Stethoscope,
    Users
} from 'lucide-react';

export const MENU_ITEMS = [
    {
        id: 1,
        key: 'home',
        title: 'Home',
        icon: Home,
        route: '',
        active: false,
        roles: ['ADMIN', 'CLIENT', 'DOCTOR'],
    },
    {
        id: 2,
        key: 'clients',
        title: 'Clients',
        icon: Users,
        route: '/clients',
        active: false,
        roles: ['ADMIN', 'DOCTOR'],
    },
    {
        id: 3,
        key: 'doctors',
        title: 'Doctors',
        icon: Stethoscope,
        route: '/doctors',
        active: false,
        roles: ['ADMIN'],
    },
    {
        id: 4,
        key: 'availability',
        title: 'Availability',
        icon: Calendar,
        route: '/availability',
        active: false,
        roles: ['ADMIN', 'DOCTOR'],
    },
    {
        id: 5,
        key: 'patientVisits',
        title: 'Patients Visits',
        icon: BookUser,
        route: '/patients',
        active: false,
        roles: ['ADMIN', 'DOCTOR'],
    },
    {
        id: 6,
        key: 'testTypes',
        title: 'Test Types',
        icon: Binoculars,
        route: '/tests',
        active: false,
        roles: ['ADMIN'],
    },
    {
        id: 7,
        key: 'documents',
        title: 'Documents',
        icon: FileText,
        route: '/documents',
        active: false,
        roles: ['ADMIN', 'CLIENT'],
    },
    // {
    //     id: 8,
    //     key: 'medicalTests',
    //     title: 'Medical Tests',
    //     icon: Activity,
    //     route: '/medical-tests',
    //     active: false,
    //     roles: ['ADMIN'],
    // },
    // {
    //     id: 9,
    //     key: 'healthConditions',
    //     title: 'Health Conditions',
    //     icon: Heart,
    //     route: '/health-conditions',
    //     active: false,
    //     roles: ['ADMIN', 'CLIENT'],
    // },
    // {
    //     id: 10,
    //     key: 'medications',
    //     title: 'Medications',
    //     icon: Pill,
    //     route: '/medications',
    //     active: false,
    //     roles: ['ADMIN', 'CLIENT'],
    // },
    // {
    //     id: 11,
    //     key: 'allergies',
    //     title: 'Allergies',
    //     icon: AlertCircle,
    //     route: '/allergies',
    //     active: false,
    //     roles: ['ADMIN', 'CLIENT'],
    // },
    // {
    //     id: 12,
    //     key: 'immunizations',
    //     title: 'Immunizations',
    //     icon: ShieldCheck,
    //     route: '/immunizations',
    //     active: false,
    //     roles: ['ADMIN', 'CLIENT'],
    // },
    {
        id: 13,
        key: 'roles',
        title: 'Roles',
        icon: Users,
        route: '/roles',
        active: false,
        roles: ['ADMIN'],
    },
    // {
    //     id: 14,
    //     key: 'contactUs',
    //     title: 'Contact Us',
    //     icon: Headset,
    //     route: '/contact-us',
    //     active: false,
    //     roles: ['ADMIN', 'CLIENT'],
    // },
    // {
    //     id: 15,
    //     key: 'aboutUs',
    //     title: 'About Us',
    //     icon: Info,
    //     route: '/about-us',
    //     active: false,
    //     roles: ['ADMIN', 'CLIENT'],
    // }
];
